version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "9100:9100"
    networks:
      - app-net
    volumes:
      - ./frontend:/app
      - /app/node_modules

  haker:
    build: ./haker
    container_name: haker
    ports:
      - "3000:3000"
    networks:
      - app-net
    volumes:
      - ./haker:/app
      - haker:/app/node_modules

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - app-net
    volumes:
      - ./backend:/app
      - backend:/app/node_modules

volumes:
  haker:
  backend:

networks:
  app-net:
    driver: bridge
